using System;
using System.Collections.Generic;

namespace WSGM.Device.Sdk.Authoring;

/// <summary>Pure fixture or capture analyzer used by plugin authoring tools.</summary>
/// <typeparam name="TObservation">Reviewable observation type.</typeparam>
/// <typeparam name="TResult">Semantic analysis type.</typeparam>
public interface IPluginObservationAnalyzer<in TObservation, out TResult>
{
    /// <summary>Stable analyzer identifier recorded in evidence.</summary>
    string AnalyzerId { get; }

    /// <summary>Analyzer implementation version recorded in evidence.</summary>
    string AnalyzerVersion { get; }

    /// <summary>Derives semantic output without touching live hardware.</summary>
    /// <param name="observation">Captured or fixture observation.</param>
    /// <returns>Deterministic semantic result.</returns>
    TResult Analyze(TObservation observation);
}

/// <summary>Whether a scaffolded file may be edited by a plugin author.</summary>
public enum PluginTemplateOwnership
{
    /// <summary>Regenerated by tooling and never hand-edited.</summary>
    Generated,

    /// <summary>Owned by the plugin author after initial creation.</summary>
    AuthorOwned,
}

/// <summary>One deterministic file in a plugin scaffold plan.</summary>
public sealed record PluginTemplateFile
{
    /// <summary>Forward-slash relative path below the plugin directory.</summary>
    public required string RelativePath { get; init; }

    /// <summary>Whether regeneration may replace this file.</summary>
    public required PluginTemplateOwnership Ownership { get; init; }

    /// <summary>UTF-8 source using LF canonical line endings.</summary>
    public required string Content { get; init; }
}

/// <summary>Inputs shared by templates and the future Roslyn generator project.</summary>
public sealed record PluginSourceGenerationRequest
{
    /// <summary>Stable package identifier.</summary>
    public required string PackageId { get; init; }

    /// <summary>Root namespace for generated declarations.</summary>
    public required string RootNamespace { get; init; }

    /// <summary>Negotiated runtime API version expected by generated glue.</summary>
    public required int RuntimeApiVersion { get; init; }
}

/// <summary>Creates the deterministic, ownership-marked core plugin template.</summary>
/// <remarks>
/// Glyph authoring files are intentionally absent until the P8 schema and normalizer are frozen.
/// The template contains no Steam selector, CDP operation, patch application, or raw hardware API.
/// </remarks>
public static class PluginProjectTemplate
{
    /// <summary>Marker placed in files that tooling may replace.</summary>
    public const string GeneratedMarker = "// <auto-generated by WSGM Device Lab>";

    /// <summary>Creates a canonical core template plan.</summary>
    /// <param name="request">Package, namespace, and runtime API metadata.</param>
    /// <returns>Files ordered by ordinal relative path.</returns>
    public static IReadOnlyList<PluginTemplateFile> Create(
        PluginSourceGenerationRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        ValidatePackageId(request.PackageId);
        ValidateNamespace(request.RootNamespace);
        if (request.RuntimeApiVersion <= 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(request),
                "Runtime API version must be positive.");
        }

        return
        [
            new PluginTemplateFile
            {
                RelativePath = "Generated/PluginMetadata.g.cs",
                Ownership = PluginTemplateOwnership.Generated,
                Content = $"{GeneratedMarker}\nnamespace {request.RootNamespace};\n\n"
                    + "internal static class PluginMetadata\n{\n"
                    + $"    internal const string PackageId = \"{Escape(request.PackageId)}\";\n"
                    + $"    internal const int RuntimeApiVersion = {request.RuntimeApiVersion};\n"
                    + "}\n",
            },
            new PluginTemplateFile
            {
                RelativePath = "Plugin.cs",
                Ownership = PluginTemplateOwnership.AuthorOwned,
                Content = $"namespace {request.RootNamespace};\n\n"
                    + "// Implement IDevicePlugin here. Keep every hardware transport private.\n",
            },
            new PluginTemplateFile
            {
                RelativePath = "README.md",
                Ownership = PluginTemplateOwnership.AuthorOwned,
                Content = $"# {request.PackageId}\n\n"
                    + "Document supported identity, verified firmware, resources, and recovery evidence.\n",
            },
        ];
    }

    private static string Escape(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal);

    private static void ValidatePackageId(string packageId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(packageId);
        foreach (char character in packageId)
        {
            if (!char.IsAsciiLetterOrDigit(character) && character is not '.' and not '-' and not '_')
            {
                throw new ArgumentException(
                    "Package ID may contain only ASCII letters, digits, dots, hyphens, and underscores.",
                    nameof(packageId));
            }
        }
    }

    private static void ValidateNamespace(string rootNamespace)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(rootNamespace);
        foreach (string segment in rootNamespace.Split('.'))
        {
            if (segment.Length == 0
                || !(char.IsLetter(segment[0]) || segment[0] == '_')
                || segment.AsSpan(1).ContainsAnyExcept(
                    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_"))
            {
                throw new ArgumentException(
                    "Root namespace must contain dot-separated identifier segments.",
                    nameof(rootNamespace));
            }
        }
    }
}
